version: "2"
services:

  app:
    image: api
    container_name: app
    restart: always
    build: ./shopcar
    ports:
      - 8080:8080
    depends_on: 
      - otel-collector

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    deploy:
      resources:
        limits:
          memory: 100M
    restart: always
    environment:
      - "GF_INSTALL_PLUGINS=grafana-opensearch-datasource"
    ports:
      - "3000:3000"

  # Jaeger - Trace
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Zipkin - Trace
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    environment:
      - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
    restart: always
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config-observability-tools/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./config-observability-tools/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"