spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

otel:
  service:
    name: shopcar
  exporter:
    otlp:
      endpoint: http://localhost:4317
      traces:
        protocol: grpc
      metrics:
        protocol: grpc
      logs:
        protocol: grpc
  logs:
    exporter: otlp



